// k6 load test — simulates realistic traffic against the REST API.
//
// Usage:
//   API_KEY=kv_... k6 run scripts/k6/load.js
//   API_KEY=kv_... BASE_URL=https://knowledgevault.app k6 run scripts/k6/load.js
//
// Ramps from 0 → 50 VUs over 60s, holds 50 VUs for 2 minutes, ramps down.
// Bail out thresholds: p(95) latency < 500ms, error rate < 1%.

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Trend, Rate } from 'k6/metrics';

const BASE = (__ENV.BASE_URL || 'http://localhost:3000').replace(/\/+$/, '');
const API_KEY = __ENV.API_KEY || '';

if (!API_KEY) {
  throw new Error('Set API_KEY env var (kv_... from Settings → API Keys).');
}

export const options = {
  stages: [
    { duration: '60s', target: 50 }, // ramp up
    { duration: '120s', target: 50 }, // steady
    { duration: '30s', target: 0 }, // ramp down
  ],
  thresholds: {
    http_req_failed: ['rate<0.01'],
    http_req_duration: ['p(95)<500'],
    'group_duration{group:::list items}': ['p(95)<300'],
    'group_duration{group:::create item}': ['p(95)<600'],
  },
};

const latencyTrend = new Trend('api_latency_ms');
const errorRate = new Rate('api_errors');

function h() {
  return {
    headers: {
      'content-type': 'application/json',
      'x-api-key': API_KEY,
    },
  };
}

export default function () {
  // Read-heavy: most traffic is list / get.
  let res = http.get(`${BASE}/api/items`, h());
  latencyTrend.add(res.timings.duration);
  errorRate.add(res.status !== 200);
  check(res, { 'list items 200': (r) => r.status === 200 });

  res = http.get(`${BASE}/api/me`, h());
  check(res, { 'me 200': (r) => r.status === 200 });
  latencyTrend.add(res.timings.duration);

  // Occasional write — every 5th virtual user creates an item.
  if (__VU % 5 === 0) {
    const body = JSON.stringify({
      title: `k6-${Date.now()}-${__VU}`,
      type: 'note',
      content: 'Generated by k6 load test.',
      location: 'inbox',
    });
    res = http.post(`${BASE}/api/items`, body, h());
    check(res, { 'create item 201-ish': (r) => r.status >= 200 && r.status < 300 });
    latencyTrend.add(res.timings.duration);
    errorRate.add(res.status >= 400);
  }

  sleep(1 + Math.random());
}

export function handleSummary(data) {
  const pct95 = data.metrics.http_req_duration?.values['p(95)'] ?? 0;
  const errPct = (data.metrics.http_req_failed?.values.rate ?? 0) * 100;
  const summary =
    `Load test finished:\n` +
    `  p(95) latency: ${Math.round(pct95)}ms\n` +
    `  error rate:    ${errPct.toFixed(2)}%\n`;
  return { stdout: summary };
}
